### ISSUE TITLE
[question] help with using tool

### ISSUE THREAD

**Issue by ayedaemon** [rkulla/vimogen#7]
I have downloaded the `vimogen.sh` and added that to my `PATH` variable as mentioned in the `README.md` file. But even after installing the plugins I can't see the respective change in the **vim** editor.

![image](https://user-images.githubusercontent.com/39592651/111113487-e260b580-8587-11eb-9b92-744c2a345eee.png)

I am new to vim and not sure if I am doing anything wrong or missing something.??

**Comment by rkulla** [comment]
Did you install the "Pathogen" plugin first?  You need to install
https://github.com/tpope/vim-pathogen/  which is what loads the plugins by
installing it and adding this line to your vimrc:

execute pathogen#infect()

**Comment by ayedaemon** [comment]
This did the trick.. Thanks!
